# -*- coding: utf-8 -*-
"""Cópia de dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGO0u4cqUc914r52eK7vxtrQ_2mpW8-m
"""

import pandas as pd
tabela = pd.read_csv("ClientesBanco.csv", encoding= "latin1")
display(tabela)

tabela = tabela.dropna()
display(tabela.info())
display(tabela.describe().round(1))

import plotly.express as px
grafico = px.histogram(tabela, x="Contatos 12m", color="Categoria")
grafico.show()

